### ISSUE TITLE
how to handle args if the event has multiple parameter

### ISSUE THREAD

**Issue by zilahir** [Cornayy/ts-discord-bot-boilerplate#7]
Hey, 

thanks for this great boilerplate! :) 

I am having some issue, with a specific event `MessageUpdate`, which has [two parameters](https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=e-messageUpdate): `oldMessage, and newMessage`

So i see, that the `args` type is any[]`, but if i do this:

```
public async run(args: any): Promise<void> {
        const message: DiscordMessage = args;
        console.debug('args', typeof message);
        if (!message.author.bot || !message.content.startsWith(this.client.settings.prefix)) {
          ...
        }
    }
```

the `typeof` should be `Array`, but it's in face an `Object` and by the content, i can verfiy that it's just the `oldMessage`, the `newMessage` is not there. 

My understanding is, that it should be `args[0]` and `args[1]`. 

Or am i misunderstanding something? How can i get both parameters for an event which has 2? 

Thank you in advance,

**Comment by Cornayy** [comment]
Hey, thanks for using my boilerplate.

I have implemented a fix for this in the latest commit. There seemed to be an issue with the spread operator while forwarding the arguments to the specific events. This means you can now access both messages with array indices/destructuring in your `MessageUpdate` event.

Let me know if this resolved your issue!

**Comment by zilahir** [comment]
Hey! Yes! indeed this was the problem, weird, i couldnt figure it out myself! :) 

Thank you for helping me out!
